---
title: "02.winners.losers"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(vegan)
library(ggplot2)
library(data.table)
library(dplyr)
library(tidyr)
library("RColorBrewer")
library("scatterplot3d")
library(ggtree)
library(phytools)
library(evobiR)
library(ggrepel)
```

## Format into Presence/Absence Matrix
```{r}
#As Planted counts
as.planted <- read.csv("../DATA/matrix.of.planted.species.csv", as.is = TRUE, sep = ",")
split(as.planted, as.planted$type) -> as.planted
as.planted$Seed -> as.planted
s.count <- as.data.frame( colSums(as.planted[-c(1:4)]) ) 
#Final Survey
sppCovMat2019 <-read.csv("../DATA/2019_VegetationCover/COVER.sppCovMat.2019.MAX.csv", as.is = TRUE)
sppCovMat2019[is.na(sppCovMat2019)] <- 0
split(sppCovMat2019, sppCovMat2019$type) -> sppCovMat2019.t
sppCovMat2019.t$Seed -> df

#Convert to presence/absence counts table of species per plot
df19 <- decostand(x=subset(df, select = Agalinis_tenuifolia:Zizia_aurea), method="pa")
df19 <- cbind(subset(sppCovMat2019.t$Seed, select = plot:Code), df19) #add plot# and type back in:
df19.S.count <- as.data.frame( colSums(df19[-c(1:4)]) ) #counts
contable.19seed <- merge(s.count, df19.S.count, by="row.names")
names(contable.19seed) <- c("species", "planted.counts", "counts.2019")

contable.19 <- contable.19seed %>%
  rowwise() %>% 
  mutate(
  prop.occ = (counts.2019/planted.counts)*100)

contable.19 <- contable.19[order(contable.19$prop.occ, decreasing = TRUE),]
contable.19 -> contable
#add other surveys:
#use the Maximum values (2016, 2017, max 2018, max 2019)

###SPLIT BY TYPE
split(df.PA, df.PA$type) -> df.PAseed
df.PAseed$Seed -> df.PAseed
split(df.PAseed, df.PAseed$year) -> df.PA.counts
lapply(df.PA.counts, function(x) as.data.frame(colSums(x[-c(1:7)]))) -> df.PA.counts
names(df.PA.counts) -> new.names
#lapply(df.PA.counts, setNames, new.names) 
#convert into dataframe with each list being a column:
do.call(cbind, lapply(df.PA.counts, data.frame)) -> df.PA.counts.new
names(df.PA.counts.new) <- new.names

df.PA.counts.new[,2:4]
plot.df.PA <- decostand(x=df.PA.counts.new[,2:4], method="pa") #
```

#Is the change in proportion of plots occupied significant?  
#fisher extact test per species to test for significant decreases
```{r}
#need count contingency table for each species for chisq.test or fisher-exact test for signficance:
contable$absent <- 0
contable$present <- contable$planted.counts - contable$counts.2019
contable[,-4] -> df
# Tranpose the dataframe to use lapply
df_t <- t(df)
colnames(df_t) <- as.vector(df_t[1,])
df_t <- df_t[-1,]
class(df_t) <- "numeric"
# Use lapply to create matrices
matrix_list <- lapply(1:ncol(df_t), function(x) matrix(as.vector(df_t[,x]), 2, 2, byrow = T))
names(matrix_list) <- colnames(df_t)
# Lots of fisher.tests
lapply(matrix_list, fisher.test) -> f.test.list #add p.adjust(p, method = p.adjust.methods, n = length(p))
sapply(f.test.list, "[[", "p.value")

which(sapply(f.test.list, "[[", "p.value") <= 0.01) -> losers

E <- as.data.frame(sapply(f.test.list[losers], function(x) {
       (p.value = x$p.value)
}))
E
```

#Plot binary success (P/A) on phylogeny per each year:
```{r}
phy <- read.tree("../DATA/phylogeny.analyzed.2016-01-05b.tre") 
phy$tip.label    #140
#drop tips not in contable
phy$tip.label[which(phy$tip.label == "Symphyotrichum_novae-angliae")] <-
  "Symphyotrichum_novae.angliae"
tree <- drop.tip(phy, which(!phy$tip.label %in% contable.19$species)) 

p <- ggtree(tree) + geom_tiplab(size=1, offset=1) + xlim(0, 350) 
legend_title1 <- "P/A Counts"
p2 <- gheatmap(p, data.frame(plot.df.PA), colnames = FALSE, width = 0.25, offset=40, colnames_position = "top",  colnames_angle = 45, hjust=0, colnames_offset_y=1,colnames_offset_x=1, font.size=2.5, low = "black", high = "white")+ theme(legend.position="none", legend.title=element_text() ) 

#labels clades
p3 <- p2 + geom_cladelabel(node=192, label="Asteraceae", align=T, color='black', offset=100) +
   geom_cladelabel(node=233, label="Lamiaceae", align=T, color='black', offset=100) +
   geom_cladelabel(node=173, "Fabaceae", align=T, color='black', offset=100) +
   geom_cladelabel(node=169, "Rosaceae", align=T, color='black', offset=100) +
   geom_cladelabel(node=147, "Poaceae", align=T, color='black', offset=100)
#ggsave(p3, file="../OUT/PA.species.tree.pdf")
```

#phylogenetic signal
```{r}
phy <- read.tree("../DATA/phylogeny.analyzed.2016-01-05b.tre") 
phy$tip.label    #140
phy$tip.label[which(phy$tip.label == "Symphyotrichum_novae-angliae")] <-
  "Symphyotrichum_novae.angliae"
tree <- drop.tip(phy, which(!phy$tip.label %in% rownames(plot.df.PA))) 

ReorderData(tree, plot.df.PA) -> plot.df.PA.ordered
#rownames(plot.df.PA.ordered) -> plot.df.PA.ordered$Species
Physig <- phylosig(tree, plot.df.PA.ordered$`2019`, method="lambda", test=TRUE)
PhysigK <- phylosig(tree, plot.df.PA.ordered$`2019`, method="K", test=TRUE)

```

#Plot species in trait space
```{r}
traits.mat <- read.csv('../DATA/ImputedMiceTraits.2016-01-06.csv', row.names = 1)
setDT(traits.mat, keep.rownames = "Species")[]
#replace "Symphyotrichum_novae.angliae" to "Symphyotrichum_novae-angliae"
traits.mat$Species <- gsub("Symphyotrichum_novae-angliae", "Symphyotrichum_novae.angliae", traits.mat$Species)

traits.mat <- traits.mat %>% filter (Species %in% names(as.planted[5:ncol(as.planted)])) 
rownames(traits.mat) <- traits.mat$Species

test.traits <- traits.mat
#convert photosynthetic pathway:
test.traits$photosyntheticPathway  <- ifelse(test.traits$photosyntheticPathway == "C3", 1,0)
test.traits <- subset(test.traits, select = -c(Species, Lifeform, wis_IL, habitClean))
rownames(test.traits) <- traits.mat$Species
Ord <- metaMDS(test.traits, maxit=10000, k=2, distance = "bray", autotransform = FALSE) #stress = 0.163257
Ord <- metaMDS(test.traits, k=2, maxit=1000000, previous.best = Ord, try = 40, autotransform = FALSE)
Species.ord <- as.data.frame(vegan::scores(Ord)) 
 
#add in the contable data above for plotting:
rownames(plot.df.PA)->  Species.ord$Species
rownames(plot.df.PA) -> plot.df.PA$Species
newDF <- left_join(Species.ord, plot.df.PA, by="Species")

newDF$`2019` <- as.factor(newDF$`2019`)
#merge contable to change species with <25% proportional plots occupied as triangle
names(contable)[1] <- "Species"
newDF.seed <- left_join(newDF, contable, by="Species")
#ADD THE CONTABLE PLUG DATA

plugSpp <- c("Hypericum_punctatum", "Dalea_candida", "Bromus_kalmii", "Asclepias_hirtella")
newDF$plugSpp[newDF$Species %in% plugSpp] <- 0 
##Add shape column
newDF.seed$shape <- ifelse(newDF.seed$prop.occ < 25 & newDF.seed$prop.occ > 0, "tri","circle")

species.in.space <- 
  ggplot(newDF.seed) +
   geom_point(aes(NMDS1, NMDS2, color=`2019`, shape=shape), size=4)  +  theme_bw() +
    geom_text_repel(aes(NMDS1, NMDS2, label = Species), data = newDF[newDF.seed$`2019` == "0",]) +
  geom_text_repel(aes(NMDS1, NMDS2, label = Species), data = newDF[newDF.seed$shape == "tri",])

###########################################
###ADD IN PLUG Plot Data
#######################################
plugDat <- read.csv(file="../data/SupplmentalFile3.PlotsOccupied.csv")

newDF.seed
counts.dat <- left_join(newDF.seed, plugDat, by=c("Species" = "species"))
counts.dat$shapePlug <- ifelse(counts.dat$total_prop < 0.25 & counts.dat$total_prop > 0, "tri","circle")

species.in.space <- 
  ggplot(newDF.seed) +
   geom_point(aes(NMDS1, NMDS2, color=`2019`, shape=shape), size=4)  +  theme_bw() +
    geom_text_repel(aes(NMDS1, NMDS2, label = Species), data = newDF[newDF.seed$`2019` == "0",]) +
  geom_text_repel(aes(NMDS1, NMDS2, label = Species), data = newDF[newDF.seed$shape == "tri",]) +
 #plus.in.spce <- ggplot(counts.dat) + 
  geom_point(aes(NMDS1, NMDS2, color=shapePlug, shape=shapePlug), data= counts.dat, size=2)  +
  geom_text_repel(aes(NMDS1, NMDS2, label = Species), data = counts.dat[counts.dat$shapePlug == "tri",]) +
  geom_text_repel(aes(NMDS1, NMDS2, label = Species), data = counts.dat[counts.dat$total_counts == "0",])

```

## species that significantly DIFFER btwen seed vs plug and plot those
```{r}
library(broom)
df.cover.long2 #from 00.load and format
#per species, group by type and compare cover
#need counts as planted from above (s.count)
rownames(s.count) -> s.count$Species
names(s.count) <- c("counts", "Species")

as.character(s.count$Species) -> s.count$Species
as.character(df.cover.long2$Species) -> df.cover.long2$Species
df.sc <- left_join(df.cover.long2, s.count, by="Species")

#from SO https://stackoverflow.com/questions/32442525/r-function-to-apply-anova-over-different-subsets-of-ones-dataset-and-collect-o
test <- df.cover.long2 %>% group_by(Species) %>% do(tidy(aov(value ~ type, data = .))) 
as.data.frame(test) -> test
newdata <- test[order(test$p.value),]
df.sc$counts <- as.numeric(df.sc$counts)
split(df.sc, df.sc$year) -> splitDF
test <- splitDF$`2019` %>% group_by(Species) %>% do(tidy(aov(value ~ type, data = ., weights = counts))) 
write.csv(test, "test.glm.for.species.diff.cover.csv")
#which species are less than 0.01?
test %>% filter(p.value < 0.01) -> sig.species
#test <- df.sc %>% group_by(Species) %>% do(tidy(glm(value ~ type, data = ., weights = counts))) 
```
